services:
  nginx:
    image: nginx
    container_name: nginx_inc
    build: 
      context: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception_network
    restart: always
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - mariadb
      - wordpress

  mariadb:
    image: mariadb
    container_name: mariadb_inc
    build:
      context: ./requirements/mariadb
    ports:
      - "3306:3306"
    networks:
      - inception_network
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file: .env

  wordpress:
    image: wordpress
    container_name: wordpress_inc
    build:
      context: ./requirements/wordpress
    ports:
      - "9000:9000"
    networks:
      - inception_network
    restart: always
    volumes:
      - wordpress-data:/var/www/html
    env_file: .env
    depends_on:
      - mariadb


volumes:
  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      type: none
      device: /home/djagusch/data/mariadb-data
      o: bind

  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
      type: none
      device: /home/djagusch/data/wordpress-data
      o: bind


networks:
  inception_network:
    name: inception_network
